[newalbum]
title = "한터차트 ─ 뮤직정보 ─ 음반신보"
url = "https://www.hanteochart.com/tobereleased"
entrySelector = "main.to-be-released div.grid div.module-item.a"
titleSelector = "div.text.pointer"
linkSelector = "*"
imageSelector = "div.img-container-wrapper div img"
contentSelector = "div.subText"
dateSelector = "div.subText"
dateFormat = "yyyy.MM.dd"
waitUntil = "networkidle"

[tobereleased]
title = "한터차트 ─ 발매 예정"
url = "https://www.hanteochart.com/tobereleased"
entrySelector = "main.to-be-released div.grid div.module-item.a"
titleSelector = "div.text.pointer"
linkSelector = "*"
imageSelector = "div.img-container-wrapper div img"
contentSelector = "div.subText"
dateSelector = "div.subText"
dateFormat = "yyyy.MM.dd"
waitUntil = "networkidle"
